/* Create the 4 tables needed for this project (Theaters, Movies, PlayLocation(which connects Theaters & Movies), and MoviePosters */
CREATE TABLE Theaters(
    TheaterID VARCHAR(6) PRIMARY KEY NOT NULL,
    TheaterName VARCHAR(256) NOT NULL,
    Street VARCHAR(256),
    City VARCHAR(128),
    LocationState VARCHAR(128),
    Zipcode VARCHAR(5) NOT NULL
);

CREATE TABLE Movies (
    MovieID VARCHAR(6) PRIMARY KEY NOT NULL,
    MovieName VARCHAR(128) NOT NULL,
    Runtime VARCHAR(64),
    Description VARCHAR(1028),
    TheaterName VARCHAR(256),
    Showtime1 VARCHAR(16),
    Showtime2 VARCHAR(16),
    Showtime3 VARCHAR(16),
    Showtime4 VARCHAR(16),
    Showtime5 VARCHAR(16)
);

CREATE TABLE PlayLocation(
    MovieID VARCHAR(6) NOT NULL,
    TheaterID VARCHAR(6) NOT NULL,
    PRIMARY KEY(MovieID, TheaterID),
    FOREIGN KEY(MovieID) REFERENCES Movies(MovieID),
    FOREIGN KEY(TheaterID) REFERENCES Theaters(TheaterID)
);

CREATE TABLE MoviePosters (
    MoviePosterID VARCHAR(6) PRIMARY KEY NOT NULL,
    MovieName VARCHAR(128) NOT NULL,
    Runtime VARCHAR(64),
    Description VARCHAR(1028),
    Poster VARCHAR(256)
);

/* Insert values into our tables */
INSERT INTO Theaters(TheaterID, TheaterName, Street, City, LocationState, Zipcode)
VALUES ('1', 'Cinemark North McKinney and XD', '1701 North, Hardin Blvd', 'McKinney', 'TX', '75071'),
       ('2', 'Cinemark Movies 14', '1701 S Central Expy', 'McKinney', 'TX', '75069'),
       ('3', 'IPIC Fairview', '321 Town Pl', 'Fairview', 'TX', '75069'),
       ('4', 'AMC CLASSIC McKinney', '900 Hardin Blvd', 'McKinney', 'TX', '75069'),
       ('5', 'Cinemark Allen 16 and XD', '921 TX-121', 'Allen', 'TX', '75013'),
       ('6', 'Moviehouse & Eatery McKinney', '8450 TX-121', 'McKinney', 'TX', '75070'),
       ('7', 'Cinemark Frisco Square and XD', '5655 Frisco Square Blvd', 'Frisco', 'TX', '75034'),
       ('8', 'AMC DINE-IN Stonebriar 24', '2601 Preston Rd #300', 'Frisco', 'TX', '75034'),
       ('9', 'Studio Movie Grill The Colony', '4800 TX-121', 'The Colony', 'TX', '75056');
       
INSERT INTO Movies(MovieID, MovieName, Runtime, Description, TheaterName, Showtime1, Showtime2, Showtime3, Showtime4, Showtime5)
VALUES ('1', 'Spider-Man: Far From Home', '130 min','Peter Parkers European vacation takes an unexpected turn when Nick Fury suddenly shows up in his hotel room. Parker soon finds himself donning the Spider-Man suit to help Fury save the world.', 'Cinemark North McKinney and XD', '9:30am', '11:45am', '1:55pm', '4:30pm', '7:15pm'),
       ('2', 'Spider-Man: Far From Home', '130 min','Peter Parkers European vacation takes an unexpected turn when Nick Fury suddenly shows up in his hotel room. Parker soon finds himself donning the Spider-Man suit to help Fury save the world.', 'Cinemark Movies 14', '10:00am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('3', 'Spider-Man: Far From Home', '130 min','Peter Parkers European vacation takes an unexpected turn when Nick Fury suddenly shows up in his hotel room. Parker soon finds himself donning the Spider-Man suit to help Fury save the world.', 'AMC CLASSIC McKinney', '10:00am', '1:45pm', '5:30pm', '8:05pm', '10:30pm'),
       ('4', 'Spider-Man: Far From Home', '130 min','Peter Parkers European vacation takes an unexpected turn when Nick Fury suddenly shows up in his hotel room. Parker soon finds himself donning the Spider-Man suit to help Fury save the world.', 'Cinemark Allen 16 and XD', '10:30am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('5', 'Spider-Man: Far From Home', '130 min','Peter Parkers European vacation takes an unexpected turn when Nick Fury suddenly shows up in his hotel room. Parker soon finds himself donning the Spider-Man suit to help Fury save the world.', 'Moviehouse & Eatery McKinney', '9:30am', '11:45am', '1:55pm', '4:30pm', '7:15pm'),
       ('6', 'Spider-Man: Far From Home', '130 min','Peter Parkers European vacation takes an unexpected turn when Nick Fury suddenly shows up in his hotel room. Parker soon finds himself donning the Spider-Man suit to help Fury save the world.', 'Cinemark Frisco Square and XD', '11:15am', '1:45pm', '5:30pm', '8:05pm', '11:00pm'),
       ('7', 'Spider-Man: Far From Home', '130 min','Peter Parkers European vacation takes an unexpected turn when Nick Fury suddenly shows up in his hotel room. Parker soon finds himself donning the Spider-Man suit to help Fury save the world.', 'AMC DINE-IN Stonebriar 24', '10:00am', '1:45pm', '5:30pm', '8:05pm', '10:30pm'),
       ('8', 'The Lion King', '118 min', 'Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny on the plains of Africa. But not everyone in the kingdom celebrates the new cubs arrival. Scar, Mufasas brother -- and former heir to the throne -- has plans of his own. The battle for Pride Rock is soon ravaged with betrayal, tragedy and drama, ultimately resulting in Simbas exile.', 'Cinemark North McKinney and XD', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('9', 'The Lion King', '118 min', 'Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny on the plains of Africa. But not everyone in the kingdom celebrates the new cubs arrival. Scar, Mufasas brother -- and former heir to the throne -- has plans of his own. The battle for Pride Rock is soon ravaged with betrayal, tragedy and drama, ultimately resulting in Simbas exile.', 'Cinemark Movies 14', '10:05am', '10:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('10', 'The Lion King', '118 min', 'Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny on the plains of Africa. But not everyone in the kingdom celebrates the new cubs arrival. Scar, Mufasas brother -- and former heir to the throne -- has plans of his own. The battle for Pride Rock is soon ravaged with betrayal, tragedy and drama, ultimately resulting in Simbas exile.', 'AMC DINE-IN Stonebriar 24', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('11', 'The Lion King', '118 min', 'Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny on the plains of Africa. But not everyone in the kingdom celebrates the new cubs arrival. Scar, Mufasas brother -- and former heir to the throne -- has plans of his own. The battle for Pride Rock is soon ravaged with betrayal, tragedy and drama, ultimately resulting in Simbas exile.', 'AMC CLASSIC McKinney', '9:45am', '1:30pm', '2:45pm', '5:45pm', '8:30pm'),
       ('12', 'The Lion King', '118 min', 'Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny on the plains of Africa. But not everyone in the kingdom celebrates the new cubs arrival. Scar, Mufasas brother -- and former heir to the throne -- has plans of his own. The battle for Pride Rock is soon ravaged with betrayal, tragedy and drama, ultimately resulting in Simbas exile.', 'Cinemark Allen 16 and XD', '10:05am', '11:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('13', 'The Lion King', '118 min', 'Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny on the plains of Africa. But not everyone in the kingdom celebrates the new cubs arrival. Scar, Mufasas brother -- and former heir to the throne -- has plans of his own. The battle for Pride Rock is soon ravaged with betrayal, tragedy and drama, ultimately resulting in Simbas exile.', 'Moviehouse & Eatery McKinney', '11:25am', '12:45pm', '3:10pm', '6:25pm', '9:10pm'),
       ('14', 'The Lion King', '118 min', 'Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny on the plains of Africa. But not everyone in the kingdom celebrates the new cubs arrival. Scar, Mufasas brother -- and former heir to the throne -- has plans of his own. The battle for Pride Rock is soon ravaged with betrayal, tragedy and drama, ultimately resulting in Simbas exile.', 'Cinemark Frisco Square and XD', '8:05am', '11:00am', '1:45pm', '7:15pm', '12:15am'),
       ('15', 'The Lion King', '118 min', 'Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny on the plains of Africa. But not everyone in the kingdom celebrates the new cubs arrival. Scar, Mufasas brother -- and former heir to the throne -- has plans of his own. The battle for Pride Rock is soon ravaged with betrayal, tragedy and drama, ultimately resulting in Simbas exile.', 'IPIC Fairview', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('16', 'Toy Story 4', '100 min', 'Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky. The adventurous journey turns into an unexpected reunion as Woodys slight detour leads him to his long-lost friend Bo Peep. ', 'Cinemark North McKinney and XD', '9:45am', '1:30pm', '6:00pm', '8:15pm', '10:00pm'),
       ('17', 'Toy Story 4', '100 min', 'Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky. The adventurous journey turns into an unexpected reunion as Woodys slight detour leads him to his long-lost friend Bo Peep. ', 'Studio Movie Grill The Colony', '8:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('18', 'Toy Story 4', '100 min', 'Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky. The adventurous journey turns into an unexpected reunion as Woodys slight detour leads him to his long-lost friend Bo Peep. ', 'AMC CLASSIC McKinney', '9:45am', '11:25pm', '4:55pm', '7:15pm', '10:05pm'),
       ('19', 'Toy Story 4', '100 min', 'Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky. The adventurous journey turns into an unexpected reunion as Woodys slight detour leads him to his long-lost friend Bo Peep. ', 'IPIC Fairview', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('20', 'Toy Story 4', '100 min', 'Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky. The adventurous journey turns into an unexpected reunion as Woodys slight detour leads him to his long-lost friend Bo Peep. ', 'AMC DINE-IN Stonebriar 24', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('21', 'Toy Story 4', '100 min', 'Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky. The adventurous journey turns into an unexpected reunion as Woodys slight detour leads him to his long-lost friend Bo Peep. ', 'Cinemark Frisco Square and XD', '10:45am', '1:00pm', '4:25pm', '6:00pm', '9:30pm'),
       ('22', 'Toy Story 4', '100 min', 'Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky. The adventurous journey turns into an unexpected reunion as Woodys slight detour leads him to his long-lost friend Bo Peep. ', 'Cinemark Movies 14', '9:00am', '12:00pm', '3:05pm', '7:00pm', '10:25pm'),
       ('23', 'Dora and the Lost City of Gold', '100 min', 'Having spent most of her life exploring the jungle, nothing could prepare Dora for her most dangerous adventure yet -- high school.', 'Cinemark Allen 16 and XD', '10:05am', '11:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('24', 'Dora and the Lost City of Gold', '100 min', 'Having spent most of her life exploring the jungle, nothing could prepare Dora for her most dangerous adventure yet -- high school.', 'AMC DINE-IN Stonebriar 24', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('25', 'Dora and the Lost City of Gold', '100 min', 'Having spent most of her life exploring the jungle, nothing could prepare Dora for her most dangerous adventure yet -- high school.', 'Moviehouse & Eatery McKinney', '11:25am', '12:45pm', '3:10pm', '6:25pm', '9:10pm'),
       ('26', 'Dora and the Lost City of Gold', '100 min', 'Having spent most of her life exploring the jungle, nothing could prepare Dora for her most dangerous adventure yet -- high school.', 'Studio Movie Grill The Colony', '10:05am', '11:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('27', 'Dora and the Lost City of Gold', '100 min', 'Having spent most of her life exploring the jungle, nothing could prepare Dora for her most dangerous adventure yet -- high school.', 'IPIC Fairview', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('28', 'Dora and the Lost City of Gold', '100 min', 'Having spent most of her life exploring the jungle, nothing could prepare Dora for her most dangerous adventure yet -- high school.', 'Cinemark North McKinney and XD', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('29', 'The Fighting Preacher', '113 min', 'Preacher Willard Bean becomes the world middleweight boxing champion in 1905, but when Joseph F. Smith asks him to step away from the limelight and serve a five-year mission in upstate New York, the Beans immediately pack their bags and travel to the East Coast.', 'Cinemark Frisco Square and XD', '8:05am', '11:00am', '1:45pm', '7:15pm', '12:15am'),
       ('30', 'The Fighting Preacher', '113 min', 'Preacher Willard Bean becomes the world middleweight boxing champion in 1905, but when Joseph F. Smith asks him to step away from the limelight and serve a five-year mission in upstate New York, the Beans immediately pack their bags and travel to the East Coast.', 'Moviehouse & Eatery McKinney', '11:25am', '12:45pm', '3:10pm', '6:25pm', '9:10pm'),
       ('31', 'The Fighting Preacher', '113 min', 'Preacher Willard Bean becomes the world middleweight boxing champion in 1905, but when Joseph F. Smith asks him to step away from the limelight and serve a five-year mission in upstate New York, the Beans immediately pack their bags and travel to the East Coast.', 'IPIC Fairview', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('32', 'The Fighting Preacher', '113 min', 'Preacher Willard Bean becomes the world middleweight boxing champion in 1905, but when Joseph F. Smith asks him to step away from the limelight and serve a five-year mission in upstate New York, the Beans immediately pack their bags and travel to the East Coast.', 'Cinemark Movies 14', '10:05am', '10:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('33', 'The Fighting Preacher', '113 min', 'Preacher Willard Bean becomes the world middleweight boxing champion in 1905, but when Joseph F. Smith asks him to step away from the limelight and serve a five-year mission in upstate New York, the Beans immediately pack their bags and travel to the East Coast.', 'Cinemark Allen 16 and XD', '10:05am', '11:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('34', 'The Fighting Preacher', '113 min', 'Preacher Willard Bean becomes the world middleweight boxing champion in 1905, but when Joseph F. Smith asks him to step away from the limelight and serve a five-year mission in upstate New York, the Beans immediately pack their bags and travel to the East Coast.', 'Studio Movie Grill The Colony', '10:05am', '11:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('35', 'Aladdin', '119 min', 'A thrilling and vibrant live-action adaptation of Disney�s animated classic, �Aladdin� is the exciting tale of the charming street rat Aladdin, the courageous and self-determined Princess Jasmine and the Genie who may be the key to their future.', 'Cinemark North McKinney and XD', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('36', 'Aladdin', '119 min', 'A thrilling and vibrant live-action adaptation of Disney�s animated classic, �Aladdin� is the exciting tale of the charming street rat Aladdin, the courageous and self-determined Princess Jasmine and the Genie who may be the key to their future.', 'Cinemark Movies 14', '10:05am', '10:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('37', 'Aladdin', '119 min', 'A thrilling and vibrant live-action adaptation of Disney�s animated classic, �Aladdin� is the exciting tale of the charming street rat Aladdin, the courageous and self-determined Princess Jasmine and the Genie who may be the key to their future.', 'AMC DINE-IN Stonebriar 24', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('38', 'Aladdin', '119 min', 'A thrilling and vibrant live-action adaptation of Disney�s animated classic, �Aladdin� is the exciting tale of the charming street rat Aladdin, the courageous and self-determined Princess Jasmine and the Genie who may be the key to their future.', 'AMC CLASSIC McKinney', '9:45am', '1:30pm', '2:45pm', '5:45pm', '8:30pm'),
       ('39', 'Aladdin', '119 min', 'A thrilling and vibrant live-action adaptation of Disney�s animated classic, �Aladdin� is the exciting tale of the charming street rat Aladdin, the courageous and self-determined Princess Jasmine and the Genie who may be the key to their future.', 'Cinemark Allen 16 and XD', '10:05am', '11:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('40', 'Aladdin', '119 min', 'A thrilling and vibrant live-action adaptation of Disney�s animated classic, �Aladdin� is the exciting tale of the charming street rat Aladdin, the courageous and self-determined Princess Jasmine and the Genie who may be the key to their future.', 'Moviehouse & Eatery McKinney', '11:25am', '12:45pm', '3:10pm', '6:25pm', '9:10pm'),
       ('41', 'Aladdin', '119 min', 'A thrilling and vibrant live-action adaptation of Disney�s animated classic, �Aladdin� is the exciting tale of the charming street rat Aladdin, the courageous and self-determined Princess Jasmine and the Genie who may be the key to their future.', 'Cinemark Frisco Square and XD', '8:05am', '11:00am', '1:45pm', '7:15pm', '12:15am'),
       ('42', 'Aladdin', '119 min', 'A thrilling and vibrant live-action adaptation of Disney�s animated classic, �Aladdin� is the exciting tale of the charming street rat Aladdin, the courageous and self-determined Princess Jasmine and the Genie who may be the key to their future.', 'IPIC Fairview', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('43', 'Aladdin', '119 min', 'A thrilling and vibrant live-action adaptation of Disney�s animated classic, �Aladdin� is the exciting tale of the charming street rat Aladdin, the courageous and self-determined Princess Jasmine and the Genie who may be the key to their future.', 'Studio Movie Grill The Colony', '10:05am', '11:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('44', 'Fast & Furious Presents: Hobbs & Shaw', '105 min', 'Ever since hulking lawman Hobbs and Shaw first faced off, the duo have swapped smack talk and body blows as theyve tried to take each other down. But when cyber-genetically enhanced anarchist Brixton gains control of an insidious bio-threat that could alter humanity forever to which Hobbs and Shaw has to work together.', 'Cinemark North McKinney and XD', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('45', 'Fast & Furious Presents: Hobbs & Shaw', '105 min', 'Ever since hulking lawman Hobbs and Shaw first faced off, the duo have swapped smack talk and body blows as theyve tried to take each other down. But when cyber-genetically enhanced anarchist Brixton gains control of an insidious bio-threat that could alter humanity forever to which Hobbs and Shaw has to work together.','Cinemark Movies 14', '10:05am', '10:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('46', 'Fast & Furious Presents: Hobbs & Shaw', '105 min', 'Ever since hulking lawman Hobbs and Shaw first faced off, the duo have swapped smack talk and body blows as theyve tried to take each other down. But when cyber-genetically enhanced anarchist Brixton gains control of an insidious bio-threat that could alter humanity forever to which Hobbs and Shaw has to work together.','Cinemark Allen 16 and XD', '10:05am', '11:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('47', 'Fast & Furious Presents: Hobbs & Shaw', '105 min', 'Ever since hulking lawman Hobbs and Shaw first faced off, the duo have swapped smack talk and body blows as theyve tried to take each other down. But when cyber-genetically enhanced anarchist Brixton gains control of an insidious bio-threat that could alter humanity forever to which Hobbs and Shaw has to work together.','IPIC Fairview', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('48', 'Fast & Furious Presents: Hobbs & Shaw', '105 min', 'Ever since hulking lawman Hobbs and Shaw first faced off, the duo have swapped smack talk and body blows as theyve tried to take each other down. But when cyber-genetically enhanced anarchist Brixton gains control of an insidious bio-threat that could alter humanity forever to which Hobbs and Shaw has to work together.','Studio Movie Grill The Colony', '10:05am', '11:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('49', 'The Art of Racing in the Rain', '96 min', 'Denny Swift is a Formula One race car driver who understands that the techniques needed on the racetrack can also be used to successfully navigate everyday life.', 'Cinemark North McKinney and XD', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('50', 'The Art of Racing in the Rain', '96 min', 'Denny Swift is a Formula One race car driver who understands that the techniques needed on the racetrack can also be used to successfully navigate everyday life.', 'AMC DINE-IN Stonebriar 24', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('51', 'The Art of Racing in the Rain', '96 min', 'Denny Swift is a Formula One race car driver who understands that the techniques needed on the racetrack can also be used to successfully navigate everyday life.','AMC CLASSIC McKinney', '9:45am', '1:30pm', '2:45pm', '5:45pm', '8:30pm'),
       ('52', 'The Art of Racing in the Rain', '96 min', 'Denny Swift is a Formula One race car driver who understands that the techniques needed on the racetrack can also be used to successfully navigate everyday life.','Moviehouse & Eatery McKinney', '11:25am', '12:45pm', '3:10pm', '6:25pm', '9:10pm'),
       ('53', 'The Art of Racing in the Rain', '96 min', 'Denny Swift is a Formula One race car driver who understands that the techniques needed on the racetrack can also be used to successfully navigate everyday life.','Cinemark Frisco Square and XD', '8:05am', '11:00am', '1:45pm', '7:15pm', '12:15am'),
       ('54', 'The Art of Racing in the Rain', '96 min', 'Denny Swift is a Formula One race car driver who understands that the techniques needed on the racetrack can also be used to successfully navigate everyday life.','IPIC Fairview', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('55', 'Crawl', '112 min', 'When a massive hurricane hits her Florida town, young Haley ignores the evacuation orders to search for her missing father, Dave. After finding him gravely injured in their family home, the two of them become trapped by the rapidly encroaching floodwaters.', 'Cinemark North McKinney and XD', '11:00am', '1:25pm', '5:15pm', '8:10pm', '11:00pm'),
       ('56', 'Crawl', '112 min', 'When a massive hurricane hits her Florida town, young Haley ignores the evacuation orders to search for her missing father, Dave. After finding him gravely injured in their family home, the two of them become trapped by the rapidly encroaching floodwaters.','Cinemark Movies 14', '10:05am', '10:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('57', 'Crawl', '112 min', 'When a massive hurricane hits her Florida town, young Haley ignores the evacuation orders to search for her missing father, Dave. After finding him gravely injured in their family home, the two of them become trapped by the rapidly encroaching floodwaters.','AMC DINE-IN Stonebriar 24', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('58', 'Crawl', '112 min', 'When a massive hurricane hits her Florida town, young Haley ignores the evacuation orders to search for her missing father, Dave. After finding him gravely injured in their family home, the two of them become trapped by the rapidly encroaching floodwaters.','AMC CLASSIC McKinney', '9:15am', '12:55pm', '3:00pm', '6:15pm', '9:30pm'),
       ('59', 'Crawl', '112 min', 'When a massive hurricane hits her Florida town, young Haley ignores the evacuation orders to search for her missing father, Dave. After finding him gravely injured in their family home, the two of them become trapped by the rapidly encroaching floodwaters.','Cinemark Allen 16 and XD', '9:00am', '1:00pm', '4:00pm', '7:00pm', '10:00pm'),
       ('60', 'Crawl', '112 min', 'When a massive hurricane hits her Florida town, young Haley ignores the evacuation orders to search for her missing father, Dave. After finding him gravely injured in their family home, the two of them become trapped by the rapidly encroaching floodwaters.','Moviehouse & Eatery McKinney', '11:25am', '12:45pm', '3:10pm', '6:25pm', '9:10pm'),
       ('61', 'The Angry Birds Movie 2', '100 min', 'Red, Chuck, Bomb and the rest of their feathered friends are surprised when a green pig suggests that they put aside their differences and unite to fight a common threat. Aggressive birds from an island covered in ice are planning to use an elaborate weapon to destroy the fowl and swine way of life.', 'Cinemark North McKinney and XD', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('62', 'The Angry Birds Movie 2', '100 min', 'Red, Chuck, Bomb and the rest of their feathered friends are surprised when a green pig suggests that they put aside their differences and unite to fight a common threat. Aggressive birds from an island covered in ice are planning to use an elaborate weapon to destroy the fowl and swine way of life.','Cinemark Movies 14', '10:05am', '10:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('63', 'The Angry Birds Movie 2', '100 min', 'Red, Chuck, Bomb and the rest of their feathered friends are surprised when a green pig suggests that they put aside their differences and unite to fight a common threat. Aggressive birds from an island covered in ice are planning to use an elaborate weapon to destroy the fowl and swine way of life.','AMC DINE-IN Stonebriar 24', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('64', 'The Angry Birds Movie 2', '100 min', 'Red, Chuck, Bomb and the rest of their feathered friends are surprised when a green pig suggests that they put aside their differences and unite to fight a common threat. Aggressive birds from an island covered in ice are planning to use an elaborate weapon to destroy the fowl and swine way of life.','AMC CLASSIC McKinney', '9:45am', '1:30pm', '2:45pm', '5:45pm', '8:30pm'),
       ('65', 'The Angry Birds Movie 2', '100 min', 'Red, Chuck, Bomb and the rest of their feathered friends are surprised when a green pig suggests that they put aside their differences and unite to fight a common threat. Aggressive birds from an island covered in ice are planning to use an elaborate weapon to destroy the fowl and swine way of life.','Cinemark Allen 16 and XD', '10:05am', '11:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('66', 'The Angry Birds Movie 2', '100 min', 'Red, Chuck, Bomb and the rest of their feathered friends are surprised when a green pig suggests that they put aside their differences and unite to fight a common threat. Aggressive birds from an island covered in ice are planning to use an elaborate weapon to destroy the fowl and swine way of life.','Moviehouse & Eatery McKinney', '11:25am', '12:45pm', '3:10pm', '6:25pm', '9:10pm'),
       ('67', 'The Angry Birds Movie 2', '100 min', 'Red, Chuck, Bomb and the rest of their feathered friends are surprised when a green pig suggests that they put aside their differences and unite to fight a common threat. Aggressive birds from an island covered in ice are planning to use an elaborate weapon to destroy the fowl and swine way of life.','Cinemark Frisco Square and XD', '8:05am', '11:00am', '1:45pm', '7:15pm', '12:15am'),
       ('68', 'The Angry Birds Movie 2', '100 min', 'Red, Chuck, Bomb and the rest of their feathered friends are surprised when a green pig suggests that they put aside their differences and unite to fight a common threat. Aggressive birds from an island covered in ice are planning to use an elaborate weapon to destroy the fowl and swine way of life.','IPIC Fairview', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('69', 'The Angry Birds Movie 2', '100 min', 'Red, Chuck, Bomb and the rest of their feathered friends are surprised when a green pig suggests that they put aside their differences and unite to fight a common threat. Aggressive birds from an island covered in ice are planning to use an elaborate weapon to destroy the fowl and swine way of life.','Studio Movie Grill The Colony', '10:05am', '11:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('70', 'Once Upon a Time...in Hollywood', '103 min', 'A faded TV actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywoods Golden Age in 1969 Los Angeles.', 'Cinemark North McKinney and XD', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('71', 'Once Upon a Time...in Hollywood', '103 min', 'A faded TV actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywoods Golden Age in 1969 Los Angeles.', 'Cinemark Movies 14', '10:05am', '10:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('72', 'Once Upon a Time...in Hollywood', '103 min', 'A faded TV actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywoods Golden Age in 1969 Los Angeles.', 'AMC DINE-IN Stonebriar 24', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('73', 'Once Upon a Time...in Hollywood', '103 min', 'A faded TV actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywoods Golden Age in 1969 Los Angeles.', 'Moviehouse & Eatery McKinney', '11:25am', '12:45pm', '3:10pm', '6:25pm', '9:10pm'),
       ('74', 'Once Upon a Time...in Hollywood', '103 min', 'A faded TV actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywoods Golden Age in 1969 Los Angeles.', 'IPIC Fairview', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('75', 'Once Upon a Time...in Hollywood', '103 min', 'A faded TV actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywoods Golden Age in 1969 Los Angeles.', 'Studio Movie Grill The Colony', '10:05am', '11:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('76', 'Avengers: Endgame', '180 min', 'Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.', 'Cinemark North McKinney and XD', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('77', 'Avengers: Endgame', '180 min', 'Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.', 'Cinemark Movies 14', '10:05am', '10:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('78', 'Avengers: Endgame', '180 min', 'Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.', 'AMC DINE-IN Stonebriar 24', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('79', 'Avengers: Endgame', '180 min', 'Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.', 'AMC CLASSIC McKinney', '9:45am', '1:30pm', '2:45pm', '5:45pm', '8:30pm'),
       ('80', 'Avengers: Endgame', '180 min', 'Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.', 'Cinemark Allen 16 and XD', '10:05am', '11:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('81', 'Avengers: Endgame', '180 min', 'Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.', 'Moviehouse & Eatery McKinney', '11:25am', '12:45pm', '3:10pm', '6:25pm', '9:10pm'),
       ('82', 'Avengers: Endgame', '180 min', 'Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.', 'Cinemark Frisco Square and XD', '8:05am', '11:00am', '1:45pm', '7:15pm', '12:15am'),
       ('83', 'Avengers: Endgame', '180 min', 'Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.', 'IPIC Fairview', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('84', 'Avengers: Endgame', '180 min', 'Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.', 'Studio Movie Grill The Colony', '10:05am', '11:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('85', 'The Art of Self Defense', '104 min', 'A man is attacked at random on the street. He enlists at a local dojo, led by a charismatic and mysterious sensei, in an effort to learn how to defend himself.', 'Cinemark North McKinney and XD', '9:45am', '12:30pm', '3:55pm', '7:15pm', '10:05pm'),
       ('86', 'The Art of Self Defense', '104 min', 'A man is attacked at random on the street. He enlists at a local dojo, led by a charismatic and mysterious sensei, in an effort to learn how to defend himself.', 'Cinemark Movies 14', '10:05am', '10:00am', '1:45pm', '5:30pm', '8:05pm'),
       ('87', 'The Art of Self Defense', '104 min', 'A man is attacked at random on the street. He enlists at a local dojo, led by a charismatic and mysterious sensei, in an effort to learn how to defend himself.', 'AMC CLASSIC McKinney', '9:45am', '1:30pm', '2:45pm', '5:45pm', '8:30pm'),
       ('88', 'The Art of Self Defense', '104 min', 'A man is attacked at random on the street. He enlists at a local dojo, led by a charismatic and mysterious sensei, in an effort to learn how to defend himself.', 'Moviehouse & Eatery McKinney', '11:25am', '12:45pm', '3:10pm', '6:25pm', '9:10pm'),
       ('89', 'The Art of Self Defense', '104 min', 'A man is attacked at random on the street. He enlists at a local dojo, led by a charismatic and mysterious sensei, in an effort to learn how to defend himself.', 'Studio Movie Grill The Colony', '10:05am', '11:00am', '1:45pm', '5:30pm', '8:05pm');

INSERT INTO PlayLocation(MovieID, TheaterID)
VALUES ('1', '1'),
       ('2', '2'),
       ('3', '4'),
       ('4', '5'),
       ('5', '6'),
       ('6', '7'),
       ('7', '8'),
       ('8', '1'),
       ('9', '2'),
       ('10', '8'),
       ('11', '4'),
       ('12', '5'),
       ('13', '6'),
       ('14', '7'),
       ('15', '3'),
       ('16', '1'),
       ('17', '9'),
       ('18', '4'),
       ('19', '3'),
       ('20', '8'),
       ('21', '7'),
       ('22', '2'),
       ('23', '5'),
       ('24', '8'),
       ('25', '6'),
       ('26', '9'),
       ('27', '3'),
       ('28', '1'),
       ('29', '7'),
       ('30', '6'),
       ('31', '3'),
       ('32', '2'),
       ('33', '5'),
       ('34', '9'),
       ('35', '1'),
       ('36', '2'),
       ('37', '8'),
       ('38', '4'),
       ('39', '5'),
       ('40', '6'),
       ('41', '7'),
       ('42', '3'),
       ('43', '9'),
       ('44', '1'),
       ('45', '2'),
       ('46', '5'),
       ('47', '3'),
       ('48', '9'),
       ('49', '1'),
       ('50', '8'),
       ('51', '4'),
       ('52', '6'),
       ('53', '7'),
       ('54', '3'),
       ('55', '1'),
       ('56', '2'),
       ('57', '8'),
       ('58', '4'),
       ('59', '5'),
       ('60', '6'),
       ('61', '1'),
       ('62', '2'),
       ('63', '8'),
       ('64', '4'),
       ('65', '5'),
       ('66', '6'),
       ('67', '7'),
       ('68', '3'),
       ('69', '9'),
       ('70', '1'),
       ('71', '2'),
       ('72', '8'),
       ('73', '6'),
       ('74', '3'),
       ('75', '9'),
       ('76', '1'),
       ('77', '2'),
       ('78', '8'),
       ('79', '4'),
       ('80', '5'),
       ('81', '6'),
       ('82', '7'),
       ('83', '3'),
       ('84', '9'),
       ('85', '1'),
       ('86', '2'),
       ('87', '4'),
       ('88', '6'),
       ('89', '9');

INSERT INTO MoviePosters(MoviePosterID, MovieName, Runtime, Description, Poster)
VALUES ('1', 'Spider-Man: Far From Home', '130 min','Peter Parkers European vacation takes an unexpected turn when Nick Fury suddenly shows up in his hotel room. Parker soon finds himself donning the Spider-Man suit to help Fury save the world.', 'spidermanfarfromhome.png'),
       ('2', 'The Lion King', '118 min', 'Simba idolizes his father, King Mufasa, and takes to heart his own royal destiny on the plains of Africa. But not everyone in the kingdom celebrates the new cubs arrival. Scar, Mufasas brother -- and former heir to the throne -- has plans of his own. The battle for Pride Rock is soon ravaged with betrayal, tragedy and drama, ultimately resulting in Simbas exile.', 'thelionking.png'),
       ('3', 'Toy Story 4', '100 min', 'Woody, Buzz Lightyear and the rest of the gang embark on a road trip with Bonnie and a new toy named Forky. The adventurous journey turns into an unexpected reunion as Woodys slight detour leads him to his long-lost friend Bo Peep. ', 'toystory4.png'),
       ('4', 'Dora and the Lost City of Gold', '100 min', 'Having spent most of her life exploring the jungle, nothing could prepare Dora for her most dangerous adventure yet -- high school.', 'doratheexplorer.png'),
       ('5', 'The Fighting Preacher', '113 min', 'Preacher Willard Bean becomes the world middleweight boxing champion in 1905, but when Joseph F. Smith asks him to step away from the limelight and serve a five-year mission in upstate New York, the Beans immediately pack their bags and travel to the East Coast.', 'thefightingpreacher.png'),
       ('6', 'Aladdin', '119 min', 'A thrilling and vibrant live-action adaptation of Disney�s animated classic, �Aladdin� is the exciting tale of the charming street rat Aladdin, the courageous and self-determined Princess Jasmine and the Genie who may be the key to their future.', 'aladdin.png'),
       ('7', 'Fast & Furious Presents: Hobbs & Shaw', '105 min', 'Ever since hulking lawman Hobbs and Shaw first faced off, the duo have swapped smack talk and body blows as theyve tried to take each other down. But when cyber-genetically enhanced anarchist Brixton gains control of an insidious bio-threat that could alter humanity forever to which Hobbs and Shaw has to work together.', 'fastfurious.png'),
       ('8', 'The Art of Racing in the Rain', '96 min', 'Denny Swift is a Formula One race car driver who understands that the techniques needed on the racetrack can also be used to successfully navigate everyday life.', 'artofracing.png'),
       ('9', 'Crawl', '112 min', 'When a massive hurricane hits her Florida town, young Haley ignores the evacuation orders to search for her missing father, Dave. After finding him gravely injured in their family home, the two of them become trapped by the rapidly encroaching floodwaters.', 'crawl.png'),
       ('10', 'The Angry Birds Movie 2', '100 min', 'Red, Chuck, Bomb and the rest of their feathered friends are surprised when a green pig suggests that they put aside their differences and unite to fight a common threat. Aggressive birds from an island covered in ice are planning to use an elaborate weapon to destroy the fowl and swine way of life.', 'angrybirds.png'),
       ('11', 'Once Upon a Time...in Hollywood', '103 min', 'A faded TV actor and his stunt double strive to achieve fame and success in the film industry during the final years of Hollywoods Golden Age in 1969 Los Angeles.', 'onceuponatime.png'),
       ('12', 'Avengers: Endgame', '180 min', 'Adrift in space with no food or water, Tony Stark sends a message to Pepper Potts as his oxygen supply starts to dwindle. Meanwhile, the remaining Avengers -- Thor, Black Widow, Captain America and Bruce Banner -- must figure out a way to bring back their vanquished allies for an epic showdown with Thanos -- the evil demigod who decimated the planet and the universe.', 'endgame.png'),
       ('13', 'The Art of Self Defense', '104 min', 'A man is attacked at random on the street. He enlists at a local dojo, led by a charismatic and mysterious sensei, in an effort to learn how to defend himself.', 'selfdefense.png');
      
/* Show all from the 4 tables */
SELECT * FROM Theaters;
SELECT * FROM Movies;
SELECT * FROM PlayLocation;
SELECT * FROM MoviePosters;

/* Drop tables from database */
/*DROP TABLE PlayLocation;
DROP TABLE Theaters;
DROP TABLE Movies;
DROP TABLE MoviePosters
*/
